travis:
  secure:
    BINSTAR_TOKEN: amn6tm+KwsFhk3K4xW7+6dZ4Sj6BAM/DLdKsyR9qAYOY4Cidv8a5QQMCPAUmeaReHaWV5j8PGWApuP5uog+f5zOfPs3+14P3VkmDNM1AYt29+o4JQwg/3MZAraLJaJOUWzNLEeWQdozkP1kOw2D7C73rwN9xRqsowO65AHIrWCjCJlMaE0YphlCPi9G2MMwqLXJDIqHCjR2ZZyrQH6D7ihL+La6rAT/A6qUwC7NoOquBZJpRy28wL3j4Aw8xDmNhySYqEoRFN8Q0yYJbh9dntb+Yyy9Qo1iJPuyKKuWuMsYdS0AYYA0psXS6YXcRrkwZbu9HFIaXlKe4xSQdo8PEWBeyG0wc2MrpCLFXn6X1g15yRIWDacunr5bXwjLD0RA79Q4vLpxQ0ebVoMnjySpGsLUQ6hY0wRHFXZpXgk9BqTz5DkVTxvEQMohqIxePq1vymFmIF7Ad3m4caRNTUqmYUsEFUUyJjIoJneqlnNnA583xg/WL1EganyPCpDYnTpQ0ecaclh8GSn/YBmHM7ayGBReUB8W6ksSEVcKHA0ji+3HFWLNXxYgRvPUJFs1v+1q858PHYWPhb2J6CCMvgg4ATrVLUbr4xOQZDhLaP4cmUIwW/BWOFoe6hHgRrHA/RZfmFBTQaMJqzVQgCIV2BHKskyPTGXt3fpNNHkhScsWbnGs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
